name: libTLDA
channels:
- conda-forge
- defaults
dependencies:
- numpy>=1.13.3
- numpydoc>=0.7.0
- matplotlib>=2.0.2
- ipython>=5.5.0
- scipy>=0.11
- Sphinx>=1.6.6
- scikit-learn>=0.15.0
- cvxopt>=1.1.9
